[package]
name = "yadb"
version = "0.0.1"
autobins = false

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "storage"
path = "src/storage/mod.rs"
edition = "2018"


[dependencies]
tokio = { version = "1.29.1", features = ["io-util", "fs"] }
log = "0.4.17"
simplelog = "0.12.1"
crossbeam-skiplist = "0.1.1"
byteorder = "1.4.3"
growable-bloom-filter = "2.0.1"
tempfile = "3.6.0"
cuckoofilter = "0.5.0"
fastmurmur3 = "0.1.2"
