[package]
name = "yadb"
version = "0.0.1"
autobins = false

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
rocksdb = "0.11.0"
log = "0.4.14"
simplelog = "0.11.0"
